#!/usr/bin/env python3
"""The cheep-cheep's own art (round 2, bug 10): the ripped ladder (row
y=110 of the hazard sheet, TWO animation frames a tier) against Koopa
Beach's CGRAM (tmp/cgram_c20.bin) -> src/fishart.inc."""
from PIL import Image
cg=open('tmp/cgram_c20.bin','rb').read()
def rgb(i):
    c=cg[i*2]|cg[i*2+1]<<8; return ((c&31)*8,((c>>5)&31)*8,((c>>10)&31)*8)
PALS=[[rgb(128+p*16+i) for i in range(16)] for p in range(8)]
im=Image.open('tmp/new/itemson-the-road-2.gif').convert('RGB'); px=im.load(); bg=px[0,0]
BOXES=[(2,110,16,15),(20,110,16,15),(38,111,15,14),(55,111,15,14),(72,112,13,13),(87,112,13,13),
       (102,113,12,12),(116,113,13,12),(131,115,11,10),(144,115,11,10)]
def quant(box,pal):
    x,y,w,h=box; out=[]; err=n=0
    for j in range(h):
        for i in range(w):
            c=px[x+i,y+j]
            if c==bg: out.append(0); continue
            k=min(range(1,16),key=lambda q:sum((pal[q][t]-c[t])**2 for t in range(3)))
            err+=sum((pal[k][t]-c[t])**2 for t in range(3)); n+=1
            out.append(k)
    return out,err//max(n,1)
errs=[sum(quant(b,PALS[p])[1] for b in BOXES) for p in range(8)]
P=min(range(8),key=lambda k:errs[k])
print('palette',P,'errors',[e//len(BOXES) for e in errs])
lines=["/* GENERATED by tools/labs/fishsheet.py: the cheep-cheep ladder from",
       " * the ripped hazard sheet, two animation frames a tier, on Koopa",
       " * Beach's OBJ palette %d (round 2, bug 10). */"%P,
       "#define SMK_FISHART_PAL %d"%P,
       "#define SMK_FISHART_N %d"%len(BOXES),
       "#define SMK_FISHART_FRAMES 2",
       "static const smk_itemart_tier SMK_FISHART[%d] = {"%len(BOXES)]
for b in BOXES:
    q,e=quant(b,PALS[P])
    lines.append("  { %d, %d, { %s } },"%(b[2],b[3],','.join(map(str,q))))
lines.append("};")
open('src/fishart.inc','w').write('\n'.join(lines)+'\n')
print('written src/fishart.inc')
