#!/usr/bin/env python3
"""Import the flattened-racer sheet (tmp/new/flattened-racers-after-thwomp.png,
the user's rip: what a Thwomp landing on a kart leaves) into src/flatart.inc:
per DRIVER, three poses in two sizes, palette-indexed against the driver
palettes in tmp/cgram.bin so every theme's re-tint applies (as itemart does).
The sheet holds 8 blocks (4 x 2) of 3 x 32px cells, big sprite on top,
small below.  Block -> driver and block -> palette were fitted: each block
quantizes to one OBJ palette with near-zero error (printed)."""
from PIL import Image
cg=open('tmp/cgram.bin','rb').read()
def rgb(i):
    c=cg[i*2]|cg[i*2+1]<<8; return ((c&31)*8,((c>>5)&31)*8,((c>>10)&31)*8)
PAL={b:[rgb(b+i) for i in range(16)] for b in (0x80,0x90,0xA0,0xB0)}
im=Image.open('tmp/new/flattened-racers-after-thwomp.png').convert('RGB'); px=im.load(); bg=px[0,0]
# driver index (SMK_DRIVERS order) -> (sheet block, palette base)
DRV=[('Mario',0,0x90),('Luigi',3,0xA0),('Bowser',2,0x80),('Peach',6,0xB0),
     ('DK Jr',1,0xB0),('Yoshi',4,0xA0),('Koopa',5,0x80),('Toad',7,0x90)]
def bbox(x0,y0,x1,y1):
    xs=[];ys=[]
    for j in range(y0,y1):
        for i in range(x0,x1):
            if px[i,j]!=bg: xs.append(i);ys.append(j)
    if not xs: return None
    return min(xs),min(ys),max(xs)+1,max(ys)+1
def quant(b,pal):
    x0,y0,x1,y1=b; out=[]; err=n=0
    for j in range(y0,y1):
        for i in range(x0,x1):
            c=px[i,j]
            if c==bg: out.append(0); continue
            k=min(range(1,16),key=lambda q:sum((pal[q][t]-c[t])**2 for t in range(3)))
            err+=sum((pal[k][t]-c[t])**2 for t in range(3)); n+=1
            out.append(k)
    return out,x1-x0,y1-y0,err//max(n,1)
lines=["/* GENERATED by tools/labs/flatsheet.py from the user's ripped sheet:",
       " * the SQUASHED racers a Thwomp leaves (bug 13), per driver, three",
       " * poses, big and small, indexed to that driver's OBJ palette so the",
       " * theme re-tints apply.  0 = transparent. */",
       "typedef struct { uint8_t w, h, pal; uint8_t px[32 * 24]; } smk_flat_tier;",
       "static const smk_flat_tier SMK_FLATART[8][6] = {"]
for name,blk,pb in DRV:
    r,c=divmod(blk,4); ent=[]
    for tier,(ya,yb) in enumerate(((0,20),(20,32))):
        for f in range(3):
            x0=c*96+f*32; y0=r*32
            b=bbox(x0,y0+ya,x0+32,y0+yb)
            q,w,h,e=quant(b,PAL[pb])
            ent.append((w,h,q,e))
    lines.append("  { /* %s: pal $%02X, err %s */"%(name,pb,[e for _,_,_,e in ent]))
    for w,h,q,e in ent:
        lines.append("    { %d, %d, 0x%02X, { %s } },"%(w,h,pb,','.join(map(str,q))))
    lines.append("  },")
    print(name, 'pal %02X'%pb, [(w,h) for w,h,_,_ in ent], 'err', [e for _,_,_,e in ent])
lines.append("};")
open('src/flatart.inc','w').write('\n'.join(lines)+'\n')
print('written src/flatart.inc')
