#!/usr/bin/env python3
"""Import the ripped road-item sheet (tmp/new/items-on-the-road.png,
QuadFactor's rip of the game's own scaler output) into src/itemart.inc:
per item, per size tier, a palette-INDEXED sprite against the game's own
OBJ palettes (tmp/cgram.bin from the oracle), so it is drawn through the
ROM's colours and a red shell is the green one on palette 1."""
import sys, os
from PIL import Image
im=Image.open('tmp/new/items-on-the-road.png').convert('RGB'); px=im.load(); bg=px[0,0]
cg=open('tmp/cgram.bin','rb').read()
def rgb(i):
    c=cg[i*2]|cg[i*2+1]<<8; return ((c&31)*8,((c>>5)&31)*8,((c>>10)&31)*8)
PALS=[[rgb(128+p*16+i) for i in range(16)] for p in range(8)]
# sprite boxes (x,y,w,h) from the sheet's connected components, tiers big -> small
SHELL=[[(7,6,16,16),(26,6,16,16),(45,6,16,16)],[(67,7,14,14),(84,7,14,15),(101,7,14,15)],[(121,9,13,12),(137,9,13,13),(153,9,13,13)],
       [(172,11,11,10),(186,10,11,12),(200,10,11,12)],[(217,14,8,8),(228,14,8,8),(239,14,8,8)],[(253,16,6,6),(262,16,7,6),(272,16,7,6)],[(285,18,4,4),(292,18,6,4),(292,18,6,4)]]
BANANA=[(7,28,16,15),(26,30,15,13),(44,32,13,11),(60,34,10,9),(73,35,8,8),(84,36,8,7),(95,37,6,6),(104,39,6,4)]
MUSH=[(6,122,16,16),(25,124,14,14),(42,126,11,12),(56,128,10,10),(69,130,8,8),(80,131,7,7),(90,133,4,5)]
EGG=[(120,123,14,16),(137,125,12,14),(152,127,10,12),(165,129,8,10),(176,131,7,8),(186,132,6,7),(195,133,5,6),(203,134,4,4)]
FIRE=[(227,124,16,16),(246,125,14,14),(263,127,13,12),(279,128,10,10),(292,130,8,8),(303,131,6,6),(312,132,5,5),(320,133,4,4)]
def quant(box,pal):
    x,y,w,h=box; out=[]; err=0
    for j in range(h):
        row=[]
        for i in range(w):
            c=px[x+i,y+j]
            if c==bg: row.append(0); continue
            best=min(range(1,16),key=lambda k:(pal[k][0]-c[0])**2+(pal[k][1]-c[1])**2+(pal[k][2]-c[2])**2)
            err+=(pal[best][0]-c[0])**2+(pal[best][1]-c[1])**2+(pal[best][2]-c[2])**2
            row.append(best)
        out.append(row)
    return out,err
def bestpal(boxes):
    errs=[sum(quant(b,PALS[p])[1] for b in boxes) for p in range(8)]
    p=min(range(8),key=lambda k:errs[k]); return p,errs
# the RED shell: the sheet has only the 16x16 (398,6).  Tier 0 is that
# sprite on its own zero-error palette (5); the smaller tiers are the green
# ladder with green index -> red index remapped by the map the two full
# size shells define, cell by cell (majority vote) - LABELLED, NOTES 192.
GPAL,RPAL=6,5
g16,_=quant((328,6,16,16),PALS[GPAL]); r16,_=quant((398,6,16,16),PALS[RPAL])
import collections
votes=collections.defaultdict(collections.Counter)
for j in range(16):
    for i in range(16):
        if g16[j][i] and r16[j][i]: votes[g16[j][i]][r16[j][i]]+=1
remap={k:v.most_common(1)[0][0] for k,v in votes.items()}
# indices the 16x16 pair never voted on: the green colour with red and
# green swapped, then the nearest red-palette colour
for k in range(1,16):
    if k not in remap:
        g=PALS[GPAL][k]; want=(g[1],g[0],g[2])
        remap[k]=min(range(1,16),key=lambda r:sum((PALS[RPAL][r][c]-want[c])**2 for c in range(3)))
print("green->red index map:",remap)
items=[("SHELL",[b for t in SHELL for b in t],3),("BANANA",BANANA,1),("MUSHROOM",MUSH,1),("EGG",EGG,1),("FIREBALL",FIRE,1)]
lines=["/* GENERATED by tools/labs/itemsheet.py from the ripped sheet (NOTES 192):",
       " * the road items' size ladders as the game's OWN scaler draws them,",
       " * quantized to the OBJ palette that fits them best.  w, h, palette,",
       " * then h rows of w palette indices (0 = transparent). */"]
for name,boxes,frames in items:
    p,errs=bestpal(boxes)
    print(f"{name}: palette {p}, errors {[int(e//1000) for e in errs]}")
    lines.append(f"#define SMK_ITEMART_{name}_PAL {p}")
    lines.append(f"#define SMK_ITEMART_{name}_N {len(boxes)}")
    lines.append(f"#define SMK_ITEMART_{name}_FRAMES {frames}")
    lines.append(f"static const smk_itemart_tier SMK_ITEMART_{name}[{len(boxes)}] = {{")
    for b in boxes:
        q,_=quant(b,PALS[p]); w,h=b[2],b[3]
        flat=','.join(str(v) for row in q for v in row)
        lines.append(f"  {{ {w}, {h}, {{ {flat} }} }},")
    lines.append("};")
# the red ladder
boxes=[b for t in SHELL for b in t]
lines.append(f"#define SMK_ITEMART_SHELL_RED_PAL {RPAL}")
lines.append(f"static const smk_itemart_tier SMK_ITEMART_SHELL_RED[{len(boxes)}] = {{")
for n,b in enumerate(boxes):
    if n<3: q,_=quant((398,6,16,16),PALS[RPAL]); w,h=16,16
    else:
        q,_=quant(b,PALS[GPAL]); w,h=b[2],b[3]
        q=[[remap.get(v,v) if v else 0 for v in row] for row in q]
    flat=','.join(str(v) for row in q for v in row)
    lines.append(f"  {{ {w}, {h}, {{ {flat} }} }},")
lines.append("};")
open('src/itemart.inc','w').write('\n'.join(lines)+'\n')
print("wrote src/itemart.inc")
