#!/usr/bin/env python3
"""Import the mole ladder from the user's ripped hazard sheet
(tmp/new/itemson-the-road-2.gif, row at y=87, left half - the right half is the explosion: a ten-step size ladder) into src/molart.inc, palette-indexed against the
Choco Island CGRAM (tmp/cgram_c10.bin) like the road items (bug 12)."""
from PIL import Image
cg=open('tmp/cgram_c10.bin','rb').read()
def rgb(i):
    c=cg[i*2]|cg[i*2+1]<<8; return ((c&31)*8,((c>>5)&31)*8,((c>>10)&31)*8)
PALS=[[rgb(128+p*16+i) for i in range(16)] for p in range(8)]
im=Image.open('tmp/new/itemson-the-road-2.gif').convert('RGB'); px=im.load(); bg=px[0,0]
BOXES=[(2,87,26,21),(30,89,22,19),(54,92,16,16),(72,94,14,14),(88,96,13,12),
       (103,96,11,12),(116,98,9,10),(127,100,7,8),(136,102,5,6),(143,104,4,4)]
def quant(box,pal):
    x,y,w,h=box; out=[]; err=n=0
    for j in range(h):
        for i in range(w):
            c=px[x+i,y+j]
            if c==bg: out.append(0); continue
            k=min(range(1,16),key=lambda q:sum((pal[q][t]-c[t])**2 for t in range(3)))
            err+=sum((pal[k][t]-c[t])**2 for t in range(3)); n+=1
            out.append(k)
    return out,err//max(n,1)
errs=[sum(quant(b,PALS[p])[1] for b in BOXES) for p in range(8)]
P=min(range(8),key=lambda k:errs[k])
print('palette',P,'errors',[e//len(BOXES) for e in errs])
lines=["/* GENERATED by tools/labs/molesheet.py from the user's ripped hazard",
       " * sheet: the Choco Island MOLE's size ladder, two animation frames a",
       " * tier, indexed to OBJ palette %d of the Choco CGRAM (bug 12). */"%P,
       "#define SMK_MOLART_PAL %d"%P,
       "#define SMK_MOLART_N %d"%len(BOXES),
       "#define SMK_MOLART_FRAMES 1",
       "static const smk_itemart_tier SMK_MOLART[%d] = {"%len(BOXES)]
for b in BOXES:
    q,e=quant(b,PALS[P])
    lines.append("  { %d, %d, { %s } },"%(b[2],b[3],','.join(map(str,q))))
lines.append("};")
open('src/molart.inc','w').write('\n'.join(lines)+'\n')
print('written src/molart.inc,',len(BOXES),'tiers*frames')
