#!/usr/bin/env python3
"""The Rainbow Road Thwomp (round 2, bug 8): the ripped BLUE sprite,
quantized to RR's own OBJ palette 1 (zero error; palette 2 is the same
sprite's flash coloring - 3 entries differ) -> src/rrthwomp.inc."""
from PIL import Image
cg=open('tmp/cgram_c34.bin','rb').read()
def rgb(i):
    c=cg[i*2]|cg[i*2+1]<<8; return ((c&31)*8,((c>>5)&31)*8,((c>>10)&31)*8)
pal=[rgb(128+16+i) for i in range(16)]
im=Image.open('tmp/new/itemson-the-road-2.gif').convert('RGB'); px=im.load(); bg=px[0,0]
x0,y0,w,h=158,20,24,32
out=[]; err=n=0
for j in range(h):
    for i in range(w):
        c=px[x0+i,y0+j]
        if c==bg: out.append(0); continue
        k=min(range(1,16),key=lambda q:sum((pal[q][t]-c[t])**2 for t in range(3)))
        err+=sum((pal[k][t]-c[t])**2 for t in range(3)); n+=1
        out.append(k)
print('err',err//max(n,1))
open('src/rrthwomp.inc','w').write(
"/* GENERATED by tools/labs/rrthwomp.py: the ripped BLUE Rainbow Road\n"
" * Thwomp on RR's own OBJ palette 1 (zero-error fit); palette 2 renders\n"
" * the same indices as the FLASH coloring (3 entries differ).  0 =\n"
" * transparent. */\n"
"#define SMK_RRTHWOMP_W %d\n#define SMK_RRTHWOMP_H %d\n"
"#define SMK_RRTHWOMP_PAL1 0x90\n#define SMK_RRTHWOMP_PAL2 0xA0\n"
"static const uint8_t SMK_RRTHWOMP[%d] = { %s };\n"
% (w,h,w*h,','.join(map(str,out))))
print('written src/rrthwomp.inc')
